<?php

class CountryTableSeeder extends Seeder {

    public function run() {
        DB::table('ne_countries')->delete();

        Model\Country::create(array('country' => 'Afghanistan', 'code' => 'AF'));
        Model\Country::create(array('country' => 'Aland Islands', 'code' => 'AX'));
        Model\Country::create(array('country' => 'Albania', 'code' => 'AL'));
        Model\Country::create(array('country' => 'Algeria', 'code' => 'DZ'));
        Model\Country::create(array('country' => 'American Samoa', 'code' => 'AS'));
        Model\Country::create(array('country' => 'Andorra', 'code' => 'AD'));
        Model\Country::create(array('country' => 'Angola', 'code' => 'AO'));
        Model\Country::create(array('country' => 'Anguilla', 'code' => 'AI'));
        Model\Country::create(array('country' => 'Antarctica', 'code' => 'AQ'));
        Model\Country::create(array('country' => 'Antigua and Barbuda', 'code' => 'AG'));
        Model\Country::create(array('country' => 'Argentina', 'code' => 'AR'));
        Model\Country::create(array('country' => 'Armenia', 'code' => 'AM'));
        Model\Country::create(array('country' => 'Aruba', 'code' => 'AW'));
        Model\Country::create(array('country' => 'Australia', 'code' => 'AU'));
        Model\Country::create(array('country' => 'Austria', 'code' => 'AT'));
        Model\Country::create(array('country' => 'Azerbaijan', 'code' => 'AZ'));
        Model\Country::create(array('country' => 'Bahamas', 'code' => 'BS'));
        Model\Country::create(array('country' => 'Bahrain', 'code' => 'BH'));
        Model\Country::create(array('country' => 'Bangladesh', 'code' => 'BD'));
        Model\Country::create(array('country' => 'Barbados', 'code' => 'BB'));
        Model\Country::create(array('country' => 'Belarus', 'code' => 'BY'));
        Model\Country::create(array('country' => 'Belgium', 'code' => 'BE'));
        Model\Country::create(array('country' => 'Belize', 'code' => 'BZ'));
        Model\Country::create(array('country' => 'Benin', 'code' => 'BJ'));
        Model\Country::create(array('country' => 'Bermuda', 'code' => 'BM'));
        Model\Country::create(array('country' => 'Bhutan', 'code' => 'BT'));
        Model\Country::create(array('country' => 'Bolivia', 'code' => 'BO'));
        Model\Country::create(array('country' => 'Bosnia and Herzegovina', 'code' => 'BA'));
        Model\Country::create(array('country' => 'Botswana', 'code' => 'BW'));
        Model\Country::create(array('country' => 'Bouvet Island', 'code' => 'BV'));
        Model\Country::create(array('country' => 'Brazil', 'code' => 'BR'));
        Model\Country::create(array('country' => 'British Indian Ocean Territory', 'code' => 'IO'));
        Model\Country::create(array('country' => 'Brunei Darussalam', 'code' => 'BN'));
        Model\Country::create(array('country' => 'Bulgaria', 'code' => 'BG'));
        Model\Country::create(array('country' => 'Burkina Faso', 'code' => 'BF'));
        Model\Country::create(array('country' => 'Burundi', 'code' => 'BI'));
        Model\Country::create(array('country' => 'Cambodia', 'code' => 'KH'));
        Model\Country::create(array('country' => 'Cameroon', 'code' => 'CM'));
        Model\Country::create(array('country' => 'Canada', 'code' => 'CA'));
        Model\Country::create(array('country' => 'Cape Verde', 'code' => 'CV'));
        Model\Country::create(array('country' => 'Cayman Islands', 'code' => 'KY'));
        Model\Country::create(array('country' => 'Central African Republic', 'code' => 'CF'));
        Model\Country::create(array('country' => 'Chad', 'code' => 'TD'));
        Model\Country::create(array('country' => 'Chile', 'code' => 'CL'));
        Model\Country::create(array('country' => 'China', 'code' => 'CN'));
        Model\Country::create(array('country' => 'Christmas Island', 'code' => 'CX'));
        Model\Country::create(array('country' => 'Cocos (Keeling) Islands', 'code' => 'CC'));
        Model\Country::create(array('country' => 'Colombia', 'code' => 'CO'));
        Model\Country::create(array('country' => 'Comoros', 'code' => 'KM'));
        Model\Country::create(array('country' => 'Congo', 'code' => 'CG'));
        Model\Country::create(array('country' => 'Congo, The Democratic Republic of the', 'code' => 'CD'));
        Model\Country::create(array('country' => 'Cook Islands', 'code' => 'CK'));
        Model\Country::create(array('country' => 'Costa Rica', 'code' => 'CR'));
        Model\Country::create(array('country' => 'Cote d\'Ivoire', 'code' => 'CI'));
        Model\Country::create(array('country' => 'Croatia', 'code' => 'HR'));
        Model\Country::create(array('country' => 'Cuba', 'code' => 'CU'));
        Model\Country::create(array('country' => 'Cyprus', 'code' => 'CY'));
        Model\Country::create(array('country' => 'Czech Republic', 'code' => 'CZ'));
        Model\Country::create(array('country' => 'Denmark', 'code' => 'DK'));
        Model\Country::create(array('country' => 'Djibouti', 'code' => 'DJ'));
        Model\Country::create(array('country' => 'Dominica', 'code' => 'DM'));
        Model\Country::create(array('country' => 'Dominican Republic', 'code' => 'DO'));
        Model\Country::create(array('country' => 'Ecuador', 'code' => 'EC'));
        Model\Country::create(array('country' => 'Egypt', 'code' => 'EG'));
        Model\Country::create(array('country' => 'El Salvador', 'code' => 'SV'));
        Model\Country::create(array('country' => 'Equatorial Guinea', 'code' => 'GQ'));
        Model\Country::create(array('country' => 'Eritrea', 'code' => 'ER'));
        Model\Country::create(array('country' => 'Estonia', 'code' => 'EE'));
        Model\Country::create(array('country' => 'Ethiopia', 'code' => 'ET'));
        Model\Country::create(array('country' => 'Falkland Islands (Malvinas)', 'code' => 'FK'));
        Model\Country::create(array('country' => 'Faroe Islands', 'code' => 'FO'));
        Model\Country::create(array('country' => 'Fiji', 'code' => 'FJ'));
        Model\Country::create(array('country' => 'Finland', 'code' => 'FI'));
        Model\Country::create(array('country' => 'France', 'code' => 'FR'));
        Model\Country::create(array('country' => 'French Guiana', 'code' => 'GF'));
        Model\Country::create(array('country' => 'French Polynesia', 'code' => 'PF'));
        Model\Country::create(array('country' => 'French Southern Territories', 'code' => 'TF'));
        Model\Country::create(array('country' => 'Gabon', 'code' => 'GA'));
        Model\Country::create(array('country' => 'Gambia', 'code' => 'GM'));
        Model\Country::create(array('country' => 'Georgia', 'code' => 'GE'));
        Model\Country::create(array('country' => 'Germany', 'code' => 'DE'));
        Model\Country::create(array('country' => 'Ghana', 'code' => 'GH'));
        Model\Country::create(array('country' => 'Gibraltar', 'code' => 'GI'));
        Model\Country::create(array('country' => 'Greece', 'code' => 'GR'));
        Model\Country::create(array('country' => 'Greenland', 'code' => 'GL'));
        Model\Country::create(array('country' => 'Grenada', 'code' => 'GD'));
        Model\Country::create(array('country' => 'Guadeloupe', 'code' => 'GP'));
        Model\Country::create(array('country' => 'Guam', 'code' => 'GU'));
        Model\Country::create(array('country' => 'Guatemala', 'code' => 'GT'));
        Model\Country::create(array('country' => 'Guernsey', 'code' => 'GG'));
        Model\Country::create(array('country' => 'Guinea', 'code' => 'GN'));
        Model\Country::create(array('country' => 'Guinea-Bissau', 'code' => 'GW'));
        Model\Country::create(array('country' => 'Guyana', 'code' => 'GY'));
        Model\Country::create(array('country' => 'Haiti', 'code' => 'HT'));
        Model\Country::create(array('country' => 'Heard Island and McDonald Islands', 'code' => 'HM'));
        Model\Country::create(array('country' => 'Holy See (Vatican City State)', 'code' => 'VA'));
        Model\Country::create(array('country' => 'Honduras', 'code' => 'HN'));
        Model\Country::create(array('country' => 'Hong Kong', 'code' => 'HK'));
        Model\Country::create(array('country' => 'Hungary', 'code' => 'HU'));
        Model\Country::create(array('country' => 'Iceland', 'code' => 'IS'));
        Model\Country::create(array('country' => 'India', 'code' => 'IN'));
        Model\Country::create(array('country' => 'Indonesia', 'code' => 'ID'));
        Model\Country::create(array('country' => 'Iran, Islamic Republic of', 'code' => 'IR'));
        Model\Country::create(array('country' => 'Iraq', 'code' => 'IQ'));
        Model\Country::create(array('country' => 'Ireland', 'code' => 'IE'));
        Model\Country::create(array('country' => 'Isle of Man', 'code' => 'IM'));
        Model\Country::create(array('country' => 'Israel', 'code' => 'IL'));
        Model\Country::create(array('country' => 'Italy', 'code' => 'IT'));
        Model\Country::create(array('country' => 'Jamaica', 'code' => 'JM'));
        Model\Country::create(array('country' => 'Japan', 'code' => 'JP'));
        Model\Country::create(array('country' => 'Jersey', 'code' => 'JE'));
        Model\Country::create(array('country' => 'Jordan', 'code' => 'JO'));
        Model\Country::create(array('country' => 'Kazakhstan', 'code' => 'KZ'));
        Model\Country::create(array('country' => 'Kenya', 'code' => 'KE'));
        Model\Country::create(array('country' => 'Kiribati', 'code' => 'KI'));
        Model\Country::create(array('country' => 'Korea, Democratic People\'s Republic of'));
        Model\Country::create(array('country' => 'Korea, Republic of', 'code' => 'KR'));
        Model\Country::create(array('country' => 'Kuwait', 'code' => 'KW'));
        Model\Country::create(array('country' => 'Kyrgyzstan', 'code' => 'KG'));
        Model\Country::create(array('country' => 'Lao People\'s Democratic Republic', 'code' => 'LA'));
        Model\Country::create(array('country' => 'Latvia', 'code' => 'LV'));
        Model\Country::create(array('country' => 'Lebanon', 'code' => 'LB'));
        Model\Country::create(array('country' => 'Lesotho', 'code' => 'LS'));
        Model\Country::create(array('country' => 'Liberia', 'code' => 'LR'));
        Model\Country::create(array('country' => 'Libyan Arab Jamahiriya', 'code' => 'LY'));
        Model\Country::create(array('country' => 'Liechtenstein', 'code' => 'LI'));
        Model\Country::create(array('country' => 'Lithuania', 'code' => 'LT'));
        Model\Country::create(array('country' => 'Luxembourg', 'code' => 'LU'));
        Model\Country::create(array('country' => 'Macao', 'code' => 'MO'));
        Model\Country::create(array('country' => 'Macedonia, The Former Yugoslav Republic of', 'code' => 'MK'));
        Model\Country::create(array('country' => 'Madagascar', 'code' => 'MG'));
        Model\Country::create(array('country' => 'Malawi', 'code' => 'MW'));
        Model\Country::create(array('country' => 'Malaysia', 'code' => 'MY'));
        Model\Country::create(array('country' => 'Maldives', 'code' => 'MV'));
        Model\Country::create(array('country' => 'Mali', 'code' => 'ML'));
        Model\Country::create(array('country' => 'Malta', 'code' => 'MT'));
        Model\Country::create(array('country' => 'Marshall Islands', 'code' => 'MH'));
        Model\Country::create(array('country' => 'Martinique', 'code' => 'MQ'));
        Model\Country::create(array('country' => 'Mauritania', 'code' => 'MR'));
        Model\Country::create(array('country' => 'Mauritius', 'code' => 'MU'));
        Model\Country::create(array('country' => 'Mayotte', 'code' => 'YT'));
        Model\Country::create(array('country' => 'Mexico', 'code' => 'MX', 'United Mexican States'));
        Model\Country::create(array('country' => 'Micronesia, Federated States of', 'code' => 'FM'));
        Model\Country::create(array('country' => 'Moldova', 'code' => 'MD'));
        Model\Country::create(array('country' => 'Monaco', 'code' => 'MC'));
        Model\Country::create(array('country' => 'Mongolia', 'code' => 'MN'));
        Model\Country::create(array('country' => 'Montenegro', 'code' => 'ME'));
        Model\Country::create(array('country' => 'Montserrat', 'code' => 'MS'));
        Model\Country::create(array('country' => 'Morocco', 'code' => 'MA'));
        Model\Country::create(array('country' => 'Mozambique', 'code' => 'MZ'));
        Model\Country::create(array('country' => 'Myanmar', 'code' => 'MM'));
        Model\Country::create(array('country' => 'Namibia', 'code' => 'NA'));
        Model\Country::create(array('country' => 'Nauru', 'code' => 'NR'));
        Model\Country::create(array('country' => 'Nepal', 'code' => 'NP'));
        Model\Country::create(array('country' => 'Netherlands', 'code' => 'NL'));
        Model\Country::create(array('country' => 'Netherlands Antilles', 'code' => 'AN'));
        Model\Country::create(array('country' => 'New Caledonia', 'code' => 'NC'));
        Model\Country::create(array('country' => 'New Zealand', 'code' => 'NZ'));
        Model\Country::create(array('country' => 'Nicaragua', 'code' => 'NI'));
        Model\Country::create(array('country' => 'Niger', 'code' => 'NE'));
        Model\Country::create(array('country' => 'Nigeria', 'code' => 'NG'));
        Model\Country::create(array('country' => 'Niue', 'code' => 'NU'));
        Model\Country::create(array('country' => 'Norfolk Island', 'code' => 'NF'));
        Model\Country::create(array('country' => 'Northern Mariana Islands', 'code' => 'MP'));
        Model\Country::create(array('country' => 'Norway', 'code' => 'NO'));
        Model\Country::create(array('country' => 'Obsolete see CD territory', 'code' => 'ZR'));
        Model\Country::create(array('country' => 'Obsolete see CS territory', 'code' => 'YU'));
        Model\Country::create(array('country' => 'Obsolete see FR territory', 'code' => 'FX'));
        Model\Country::create(array('country' => 'Obsolete see LT territory', 'code' => 'LX'));
        Model\Country::create(array('country' => 'Obsolete see RS or ME territory', 'code' => 'CS'));
        Model\Country::create(array('country' => 'Obsolete see TL territory', 'code' => 'TP'));
        Model\Country::create(array('country' => 'Oman', 'code' => 'OM'));
        Model\Country::create(array('country' => 'Pakistan', 'code' => 'PK'));
        Model\Country::create(array('country' => 'Palau', 'code' => 'PW'));
        Model\Country::create(array('country' => 'Palestinian Territory,Occupied', 'code' => 'PS'));
        Model\Country::create(array('country' => 'Panama', 'code' => 'PA'));
        Model\Country::create(array('country' => 'Papua New Guinea', 'code' => 'PG'));
        Model\Country::create(array('country' => 'Paraguay', 'code' => 'PY'));
        Model\Country::create(array('country' => 'Peru', 'code' => 'PE'));
        Model\Country::create(array('country' => 'Philippines', 'code' => 'PH'));
        Model\Country::create(array('country' => 'Pitcairn', 'code' => 'PN'));
        Model\Country::create(array('country' => 'Poland', 'code' => 'PL'));
        Model\Country::create(array('country' => 'Portugal', 'code' => 'PT'));
        Model\Country::create(array('country' => 'Puerto Rico', 'code' => 'PR'));
        Model\Country::create(array('country' => 'Qatar', 'code' => 'QA'));
        Model\Country::create(array('country' => 'Reunion', 'code' => 'RE'));
        Model\Country::create(array('country' => 'Romania', 'code' => 'RO'));
        Model\Country::create(array('country' => 'Russian Federation', 'code' => 'RU'));
        Model\Country::create(array('country' => 'Rwanda', 'code' => 'RW'));
        Model\Country::create(array('country' => 'Saint Barthelemy', 'code' => 'BL'));
        Model\Country::create(array('country' => 'Saint Helena', 'code' => 'SH'));
        Model\Country::create(array('country' => 'Saint Kitts and Nevis', 'code' => 'KN'));
        Model\Country::create(array('country' => 'Saint Lucia', 'code' => 'LC'));
        Model\Country::create(array('country' => 'Saint Martin (French part)', 'code' => 'MF'));
        Model\Country::create(array('country' => 'Saint Pierre and Miquelon', 'code' => 'PM'));
        Model\Country::create(array('country' => 'Saint Vincent and the Grenadines', 'code' => 'VC'));
        Model\Country::create(array('country' => 'Samoa', 'code' => 'WS'));
        Model\Country::create(array('country' => 'San Marino', 'code' => 'SM'));
        Model\Country::create(array('country' => 'Sao Tome and Principe', 'code' => 'ST'));
        Model\Country::create(array('country' => 'Saudi Arabia', 'code' => 'SA'));
        Model\Country::create(array('country' => 'Senegal', 'code' => 'SN'));
        Model\Country::create(array('country' => 'Serbia', 'code' => 'RS'));
        Model\Country::create(array('country' => 'Seychelles', 'code' => 'SC'));
        Model\Country::create(array('country' => 'Sierra Leone', 'code' => 'SL'));
        Model\Country::create(array('country' => 'Singapore', 'code' => 'SG'));
        Model\Country::create(array('country' => 'Slovakia', 'code' => 'SK'));
        Model\Country::create(array('country' => 'Slovenia', 'code' => 'SI'));
        Model\Country::create(array('country' => 'Solomon Islands', 'code' => 'SB'));
        Model\Country::create(array('country' => 'Somalia', 'code' => 'SO'));
        Model\Country::create(array('country' => 'South Africa', 'code' => 'ZA'));
        Model\Country::create(array('country' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS'));
        Model\Country::create(array('country' => 'Spain', 'code' => 'ES'));
        Model\Country::create(array('country' => 'Sri Lanka', 'code' => 'LK'));
        Model\Country::create(array('country' => 'Sudan', 'code' => 'SD'));
        Model\Country::create(array('country' => 'Suriname', 'code' => 'SR'));
        Model\Country::create(array('country' => 'Svalbard and Jan Mayen', 'code' => 'SJ'));
        Model\Country::create(array('country' => 'Swaziland', 'code' => 'SZ'));
        Model\Country::create(array('country' => 'Sweden', 'code' => 'SE'));
        Model\Country::create(array('country' => 'Switzerland', 'code' => 'CH'));
        Model\Country::create(array('country' => 'Syrian Arab Republic', 'code' => 'SY'));
        Model\Country::create(array('country' => 'Taiwan', 'code' => 'TW'));
        Model\Country::create(array('country' => 'Tajikistan', 'code' => 'TJ'));
        Model\Country::create(array('country' => 'Tanzania, United Republic of', 'code' => 'TZ'));
        Model\Country::create(array('country' => 'Thailand', 'code' => 'TH'));
        Model\Country::create(array('country' => 'Timor-Leste', 'code' => 'TL'));
        Model\Country::create(array('country' => 'Togo', 'code' => 'TG'));
        Model\Country::create(array('country' => 'Tokelau', 'code' => 'TK'));
        Model\Country::create(array('country' => 'Tonga', 'code' => 'TO'));
        Model\Country::create(array('country' => 'Trinidad and Tobago', 'code' => 'TT'));
        Model\Country::create(array('country' => 'Tunisia', 'code' => 'TN'));
        Model\Country::create(array('country' => 'Turkey', 'code' => 'TR'));
        Model\Country::create(array('country' => 'Turkmenistan', 'code' => 'TM'));
        Model\Country::create(array('country' => 'Turks and Caicos Islands', 'code' => 'TC'));
        Model\Country::create(array('country' => 'Tuvalu', 'code' => 'TV'));
        Model\Country::create(array('country' => 'Uganda', 'code' => 'UG'));
        Model\Country::create(array('country' => 'Ukraine', 'code' => 'UA'));
        Model\Country::create(array('country' => 'United Arab Emirates', 'code' => 'AE'));
        Model\Country::create(array('country' => 'United Kingdom', 'code' => 'GB'));
        Model\Country::create(array('country' => 'United States', 'code' => 'US'));
        Model\Country::create(array('country' => 'United States Minor Outlying Islands', 'code' => 'UM'));
        Model\Country::create(array('country' => 'Uruguay', 'code' => 'UY'));
        Model\Country::create(array('country' => 'Uzbekistan', 'code' => 'UZ'));
        Model\Country::create(array('country' => 'Vanuatu', 'code' => 'VU'));
        Model\Country::create(array('country' => 'Venezuela', 'code' => 'VE'));
        Model\Country::create(array('country' => 'Viet Nam', 'code' => 'VN'));
        Model\Country::create(array('country' => 'Virgin Islands, British', 'code' => 'VG'));
        Model\Country::create(array('country' => 'Virgin Islands, U.S.', 'code' => 'VI'));
        Model\Country::create(array('country' => 'Wallis and Futuna', 'code' => 'WF'));
        Model\Country::create(array('country' => 'Western Sahara', 'code' => 'EH'));
        Model\Country::create(array('country' => 'Yemen', 'code' => 'YE'));
        Model\Country::create(array('country' => 'Zambia', 'code' => 'ZM'));
        Model\Country::create(array('country' => 'Zimbabwe', 'code' => 'ZW'));
    }

}
