@include('.shared.header')
@include('shared.navbar')
@yield('content')
@include('shared.jobs')
@include('shared.services')
@include('shared.news')
@include('.shared.modals')
@include('.shared.footer')
